export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    "Generate an image of a sunset over a mountain range",
    "Generate an image of a sunset over a mountain range",
    "Create a picture of a tropical beach with clear blue water",
    "Make a rendering of a city skyline at night",
    "Produce an image of a dense forest with a waterfall",
    "Generate a picture of a snowy winter landscape with a cabin",
    "Create an image of a desert with a sandstorm",
    "Make a rendering of a waterfall in a jungle setting",
    "Produce a picture of a hot air balloon flying over a rural area",
    "Generate an image of a lighthouse on a rocky coast",
    "Create a picture of a beautiful garden with a pond and colorful flowers",
    "Generate a picture of a castle on a hilltop",
    "Create an image of a rainbow over a field of flowers",
    "Make a rendering of a modern cityscape with skyscrapers",
    "Produce a picture of a moonlit night sky with stars and a crescent moon",
    "Generate an image of a sunset over a lake with a dock and canoe",
    "Create a picture of a dense jungle with a hidden temple",
    "Make a rendering of a waterfall in a canyon",
    "Produce an image of a snowy mountain range with a ski resort",
    "Generate a picture of a beach with clear blue water and palm trees",
    "Create an image of a desert oasis with a pond and palm trees",
    "Make a rendering of a forest with a stream and a bridge",
    "Produce a picture of a hot air balloon flying over a city skyline",
    "Generate an image of a rainbow over a waterfall",
    "Create a picture of a sunset over a lake with a cabin",
    "Make a rendering of a city at night with reflections on the water",
    "Produce a picture of a beach with crystal clear water and white sand",
    "Generate an image of a forest with a cabin and a fire pit",
    "Create a picture of a island with palm trees and a sandy beach",
    "Make a rendering of a cityscape with modern skyscrapers and a sunset",
    "Produce an image of a mountain range with a scenic lookout point"
];